---
- name: Ansible file
  hosts: webservers
  gather_facts: no
  become: yes
  tasks:
    - name: copy the file to the server
      copy:
        src: /var/lib/jenkins/jobs/Ansible_project/workspace/inputFile/index.html
        dest: /opt/inputFile
        owner: root
        group: root
        mode: 550
        
    - name: copy the file
      copy:
        src: /var/lib/jenkins/jobs/Ansible_project/workspace/docker_c/
        dest: /opt/docker_c
        owner: mdwuser
        group: mdwuser
        mode: 550
        
    - name: run shell cmd
      shell:
        "chmod +x /opt/docker_c/docker-compose.yml" 
             
    - name: run shell cmd
      async: 30
      poll: 0
      shell:
        "cd /opt/docker_c && docker-compose up"
        