---
- name: Ansible file
  hosts: webservers
  gather_facts: no
  become: yes
  tasks:
    - name: Install update on ubuntu
      shell:
        "apt-install update"
    - name: install docker engine
      delay: 10
      shell:
        "apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin" 
    
