---
- name: Ansible file
  hosts: webservers
  gather_facts: no
  become: yes
  tasks:
    - name: install docker engine
      delay: 10
      shell:
        "sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin" 