---
- name: Ansible file
  hosts: webservers
  gather_facts: no
  become: yes
  tasks:
    - name: copy the file to the server
      copy:
        src: /var/lib/jenkins/jobs/Ansible_project/workspace/inputFile/
        dest: /opt/inputFile/
       
        
    - name: copy the file
      copy:
        src: /var/lib/jenkins/jobs/Ansible_project/workspace/docker_c/
        dest: /opt/docker_c/
      
             
    - name: run shell cmd
      async: 30
      poll: 0
      shell:
        "cd /opt/docker_c && docker-compose up"
